//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WapiOgranci
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dersler
    {
        public int Id { get; set; }
        public string DersAdi { get; set; }
        public int OgrId { get; set; }
    
        public virtual Ogrenciler Ogrenciler { get; set; }
    }
}
